USE [master]
GO

/****** Object:  Database [DatabasInlämning2]    Script Date: 2016-04-18 15:35:30 ******/
DROP DATABASE [DatabasInlämning2]
GO

/****** Object:  Database [DatabasInlämning2]    Script Date: 2016-04-18 15:35:30 ******/
CREATE DATABASE [DatabasInlämning2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DatabasInlämning2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DatabasInlämning2.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DatabasInlämning2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DatabasInlämning2_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DatabasInlämning2] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DatabasInlämning2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DatabasInlämning2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DatabasInlämning2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DatabasInlämning2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DatabasInlämning2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DatabasInlämning2] SET ARITHABORT OFF 
GO

ALTER DATABASE [DatabasInlämning2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DatabasInlämning2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DatabasInlämning2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DatabasInlämning2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DatabasInlämning2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DatabasInlämning2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DatabasInlämning2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DatabasInlämning2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DatabasInlämning2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DatabasInlämning2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DatabasInlämning2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DatabasInlämning2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DatabasInlämning2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DatabasInlämning2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DatabasInlämning2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DatabasInlämning2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DatabasInlämning2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DatabasInlämning2] SET RECOVERY FULL 
GO

ALTER DATABASE [DatabasInlämning2] SET  MULTI_USER 
GO

ALTER DATABASE [DatabasInlämning2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DatabasInlämning2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DatabasInlämning2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DatabasInlämning2] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DatabasInlämning2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DatabasInlämning2] SET  READ_WRITE 
GO

